### ISSUE TITLE
(v2.6.3) Only trust X-Forwarded-For when request is from a trusted proxy 

### ISSUE THREAD

**Issue by adryd325** [zhangjiayin/caddy-geoip2#1]
For upcoming version v2.6.3, there's a new global trusted_proxies directive. Perhaps an option to only trust X-Forwarded-For when the connection is trusted.

**Comment by zhangjiayin** [comment]
so  refered to : https://github.com/zhangjiayin/caddy-geoip2/blob/main/geoip2.go#L226-L254

cloud you provider some suggestions?

**Comment by adryd325** [comment]
this feature isn't avalible in 2.6.2, so we'd probably want to wait for 2.6.3 to release

```go
// Check if the proxy is trusted
trustedProxy := caddyhttp.GetVar(r.Context(), caddyhttp.TrustedProxyVarKey).(bool)


// Use the client ip from the 'X-Forwarded-For' header, if available.
if fwdFor := r.Header.Get("X-Forwarded-For"); fwdFor != "" && trustedProxy {
	ips := strings.Split(fwdFor, ", ")
	ip = ips[0]
} else {```

**Comment by adryd325** [comment]
these are the relevant changes 
https://github.com/caddyserver/caddy/pull/5103
https://github.com/caddyserver/caddy/pull/5328

**Comment by zhangjiayin** [comment]
OK
 waiting  for 2.6.3 to release. and we'll keep this issue opened.

Thank you .

**Comment by adryd325** [comment]
In the meantime I wanted to thank you for making this really good GeoIP plugin. The others were lacking and this one is close to feature complete!

**Comment by zhangjiayin** [comment]
I've made changes for the v2.6.3 #2 
the directive: geoip2_vars should be 
```
strict: only use remote IP address
wild: use X-Forwarded-For if it exists
trusted_proxies: use X-Forwarded-For if exists when trusted_proxies if valid
default:trusted_proxies
```
I think it should be what you described
And I will merge it later.

**Comment by adryd325** [comment]
This is perfect! Thank you so much!
