### ISSUE TITLE
How to use geoip2 to block/allow access from a specific region?

### ISSUE THREAD

**Issue by KureAtYungkurrinthi** [zhangjiayin/caddy-geoip2#7]
Hello,

I tried using this module to restrict or permit access from a particular area to my site, but I was unsuccessful since I couldn't figure out how to include such constraints in the request match.

It will be really appreciated if there is guidance on how to achieve this.

best wishes,
Kure

**Comment by zhangjiayin** [comment]
that what you want maybe related to[  Request Matcher](https://caddyserver.com/docs/caddyfile/matchers#expression)
the configuration maybe like this

```
  @denied {
    expression {geoip2.country_code} ==  "US"
  }

  route {
    respond @denied "Access denied" 403 {
      close
    }
  }
```

**Comment by zhangjiayin** [comment]
hi @KureAtYungkurrinthi   could I close this issue ?

**Comment by KureAtYungkurrinthi** [comment]
> hi @KureAtYungkurrinthi could I close this issue ?

Sorry for the late response. I added related example configurations to the document, in case anyone else is also confused.

**Comment by samumatic** [comment]
I tried to use the Request Matcher with a domain wildcard:

```
*.domain.com {
	encode gzip
	crowdsec
	geoip2_vars trusted_proxies

	# Add country and state code to the header
	header geoip-country "{geoip2.country_code}"

	log {
		output file /var/log/caddy/access.log
	}

	@geoip expression {geoip2.country_code} !=  "DE"
	abort @geoip

	@url1 host url1.domain.com
	handle @url1 {
		reverse_proxy container:9999
	}

	@url2 host url2.domain.com
	handle @url2 {
		reverse_proxy container:8888
	}

	handle {
		abort
	}
}
```

But it didn't work. Does the abort command not work here, or how do I define this in a wildcard section?
